# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostbasic',
            name='os_platform',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='系统'),
        ),
        migrations.AlterField(
            model_name='hostbasic',
            name='os_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
