# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-17 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasset', '0002_auto_20180417_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostbasic',
            name='hostname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
