# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-17 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasset', '0003_auto_20180417_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmemory',
            name='size',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='大小'),
        ),
    ]
