# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasset', '0004_auto_20180417_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdisk',
            name='model',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='磁盘厂商(型号)'),
        ),
        migrations.AlterField(
            model_name='hostnic',
            name='netmask',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='子网掩码'),
        ),
        migrations.AlterField(
            model_name='hostnic',
            name='up',
            field=models.BooleanField(default=False, verbose_name='网卡状态'),
        ),
    ]
