# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasset', '0005_auto_20180418_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostnic',
            name='hwaddr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='网卡mac地址'),
        ),
    ]
